FROM node:alpine

RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api
COPY ./app/package.json .
COPY ./app/yarn.lock .
RUN yarn --pure-lockfile
COPY ./api/. .

EXPOSE 8080
CMD ["yarn", "serve"]
