version: "3"
services:
    server:
        build:
            context: ../.
            dockerfile: docker/server/Dockerfile.dev
        image: gow:server
        deploy:
            resources: # Set these values when you know what you do!
                limits:
                    cpus: "0.001"
                    memory: 4096M
                reservations:
                    cpus: "0.0001"
                    memory: 4096M
        ports:
            - "80:80" # Connect localhost 80 port to container 80 port
        links: # Link services to access http://app and  http://api inside the container
            - api:api
            - app:app
    app:
        deploy:
            resources: # Set these values when you know what you do!
                limits:
                    cpus: "0.001"
                    memory: 4096M
                reservations:
                    cpus: "0.0001"
                    memory: 4096M
        build:
            context: ../.
            dockerfile: docker/app/Dockerfile.dev
        image: gow:app
        environment:
            - NODE_ENV=development
        volumes: # For webpack dev server to use our local files
            - ./../app:/usr/src/app
            - /usr/src/app/node_modules/
        ports:
            - "3000:3000" # For docker to now where to redirect HMR queries\
        stdin_open: true
    api:
        deploy:
            resources: # Set these values when you know what you do!
                limits:
                    cpus: "0.001"
                    memory: 4096M
                reservations:
                    cpus: "0.0001"
                    memory: 4096M
        build:
            context: ../.
            dockerfile: docker/api/Dockerfile.dev
        image: gow:api
        environment:
            - DB_NAME=gowdb
            - DB_USER=gowuser
            - DB_PASSWORD=gowpassword
            - DB_HOST="db"
            - DB_PORT=5432
            - NODE_ENV=development
        links:
            - db:db
            - gfs:gfs
        volumes:
            - ./../api:/usr/src/api
            - /usr/src/app/node_modules/
        ports:
            - "8080"
        depends_on:
            - "db"
            - "gfs"
    db:
        build:
            context: ../.
            dockerfile: docker/db/Dockerfile.dev
        env_file: db/psql.dev.env
        image: gow:db
        ports:
            - "5431:5432"
    gfs:
        build:
            context: ../.
            dockerfile: docker/gfs/Dockerfile.dev
        image: gow:gfs
        volumes:
            - mongodata:/data/db
        ports:
            - "27017-27019:27017-27019"
volumes:
    mongodata:
